### ISSUE TITLE
navbar changes

### ISSUE THREAD

**Issue by snrakshith** [nisabmohd/Documentation-Template#1]
- I tried using your template, only documentation tab in the navbar is working fine but facing issue in adding content under other tabs like blog, example 
- Please consider making route-config.ts dynamic to except routes under other different nav sections like blog

**Comment by nisabmohd** [comment]
This template's primary motto is "only documentation," "routing can be configured however the user wishes," and "there are dummy hyperlinks in the navbar that are there for reference only," which closes the issue.
